version: '1.0'

services:
  mysqldb:
    container_name: mysqldatabase
    image: mysql:latest
    ports:
      - '3000:3000'
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    env_file:
      - ./db.env

volumes:
  mysql_data:
